#ifndef ARP_SHADOW_INCLUDE
#define ARP_SHADOW_INCLUDE

#define MAX_SHADOWED_DIRECTIONAL_COUNT 4

CBUFFER_START(_CustomShadows)
    float4x4 _DirectonalShadowMatrics[MAX_SHADOWED_DIRECTIONAL_COUNT];
    float4 _DirectonalShadowData[MAX_SHADOWED_DIRECTIONAL_COUNT];
CBUFFER_END

#endif
